theme: minima
title: Your new title
author: GitHub test User 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem Ipsum is simply dummy text of the printing and typesetting industry.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
